name: Release

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - none

env:
  NPM_TOKEN: ${{secrets.NPM_TOKEN}}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Release
      run: yarn release

    - name: Publish
      run: npm publish --access public